name: Push to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  push-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Fix shallow clone issue

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # ✅ Your Hugging Face token stored in GitHub secrets
        run: |
          git remote add space https://Anandhaprasad18:${HF_TOKEN}@huggingface.co/spaces/Anandhaprasad18/MoodTuneBot
          git push --force space main  # ✅ Use your actual space path
