name: Push to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  push-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fix shallow clone issue

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://heisenberg-walterwhite:${HF_TOKEN}@huggingface.co/spaces/heisenberg-walterwhite/musicbot
          git push --force space main
